# Dependencies
markdown:	kramdown
highlighter: 	rouge
remote_theme:   fongandrew/hydeout

# Setup
title: Welcome to W17ch3r Security
email: w17ch3r87@gmail.com	
description: 'Hacking,Fitness,Gaming'
url: https://www.w17ch3rs3c.com
github_username:  w17ch3rs3cur1ty

author:
  name:		'Trevor Holt'
  url:		 https://www.w17ch3rs3c.com

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-seo
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


#Skeletons for _posts & _pages
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:categories/:title/   
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default

#Include _pages directory for pages to be included in site
include: [_pages]
